# EvaluationSurprisal.py
# Surprisal evaluation / Belef Elicitation of theory laws using repeated sampling of LLM-as-a-judge beliefs

import os
import json

from Struct import *
from PaperStore import *
from PaperFinderRequests import *
from Theorizer import *

from TheorizerProcessing import *

from ExtractionUtils import *

from EvaluationCommon import *


#
#   Surprisal Analysis
#

# Rate a single law for surprisal using LLM-as-a-judge
def rate_theory_law_surprisal(law:dict, model_str:str, max_tokens:int=32000, temperature=1.0):
    def mkPrompt(law:dict):
        prompt = "Below you will see a specific theory statement/theory law, as well as a broader theory description for context.  These theories/theory statements were generated by an automated scientific discovery system, and are of unknown quality.\n"
        prompt += "Your task is to determine how likely you believe the theory_statement/theory_law is of being true. You will express your answer as a real-valued probability that is between 0 (definitely not true) and 1 (definitely true).\n"
        prompt += "As part of your reasoning for determining this probability, you will be asked to provide a brief, information-dense list of reasons why the theory_statement/theory_law might be true, and reasons for why it might be false, based on your knowledge.\n"
        prompt += "\n"

        prompt += "Theory Statement/Law (including theory description as background):\n"
        prompt += "```\n"
        prompt += json.dumps(law, indent=4)
        prompt += "\n```\n"
        prompt += "\n"

        prompt += "Answer with a JSON object (written between codeblocks, ```) with a single key `probability_true`, and a value between 0 and 1, where 0 is definitely false, and 1 is definitely true.  For reference, 0.1 would be strongly leaning false, 0.9 strongly leaning true, and 0.5 as genuinely equally probable. Example values: 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0.\n"
        prompt += "Example Output:\n"
        prompt += "```\n"
        prompt += "{\n"
        prompt += '  \"thought_why_might_be_true\": \"A short 1-2 sentence string giving reasons for why the theory statement/theory law might be true\",\n'
        prompt += '  \"thought_why_might_be_false\": \"A short 1-2 sentence string giving reasons for why the theory statement/theory law might be false\",\n'
        prompt += '  \"probability_true\": 0.0\n'
        prompt += "}\n"
        prompt += "```\n"
        prompt += "\n"
        prompt += "You are welcome to think before you provide your response, but the last thing you write should be the JSON output, between codeblocks.\n"
        prompt += "Now, please provide your answer.\n"

        return prompt

    # First, we'll sanitize some information from the `law`
    # Remove `theory_name`
    if ("theory_id" in law):
        del law["theory_id"]
    # Remove `supporting_evidence`
    if ("law" in law) and ("supporting_evidence" in law["law"]):
        del law["law"]["supporting_evidence"]
    # Remove `qual_or_quant`
    if ("law" in law) and ("qual_or_quant" in law["law"]):
        del law["law"]["qual_or_quant"]
    # Remove `novelty_evaluation`
    if ("law" in law) and ("novelty_evaluation" in law["law"]):
        del law["law"]["novelty_evaluation"]


    total_cost = 0.0
    prompt = mkPrompt(law)
    responseJSON, responseText, cost = getLLMResponseJSON(promptStr=prompt, model=model_str, maxTokens=max_tokens, temperature=temperature, jsonOut=False, max_generation_time_seconds=300)
    total_cost += cost

    probability_true = None
    try:
        probability_true = responseJSON.get("probability_true", None)
    except Exception as e:
        print("Error parsing `probability_true` JSON: " + str(e))
        probability_true = None

    packed = {
        "probability_true": probability_true,
        "response": responseJSON,
        "total_cost": total_cost,
    }
    return packed


# This function repeatedly samples the LLM to get an average surprisal rating for a law
def rate_theory_law_surprisal_repeated_sampling(law:dict, model_str:str, max_tokens:int=32000, temperature=1.0, num_samples:int=10, max_concurrent_requests:int=5):
    probabilities = []
    total_cost = 0.0

    import concurrent.futures
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_concurrent_requests) as executor:
        futures = []
        for i in range(num_samples):
            futures.append(executor.submit(rate_theory_law_surprisal, law, model_str, max_tokens, temperature))

        for future in concurrent.futures.as_completed(futures):
            result = future.result()
            try:
                probability = result["probability_true"]
                if (isinstance(probability, float)):
                    probabilities.append(result["probability_true"])
                total_cost += result.get("total_cost", 0.0)
            except Exception as e:
                print("Error in getting result from future: " + str(e))

    avg_probability = None
    if (len(probabilities) > 0):
        avg_probability = sum(probabilities) / len(probabilities)

    packed = {
        "average_probability_true": avg_probability,
        "probabilities": probabilities,
        "num_samples_requested": num_samples,
        "model_str": model_str,
        "temperature": temperature,
        "total_cost": total_cost,
        "max_tokens": max_tokens,
        "law": law
    }

    return packed


# This is the main function to do LLM-based surprisal evaluation of a set of laws
def do_llm_law_evaluation_surprise(filename_in:str, model_str:str, num_workers:int=50, num_samples = 10, DEBUG_LIMIT:int=0):
    # Make a timestamped output filename
    filename_out = filename_in.replace(".json", ".surprise_evaluated." + time.strftime("%Y%m%d-%H%M%S") + ".json")

    # Load a list of laws
    laws = None
    with open(filename_in, "r") as f:
        laws = json.load(f)

    print("Loaded " + str(len(laws)) + " laws from file.")

    # DEBUG LIMIT
    if (DEBUG_LIMIT > 0):
        laws = laws[:DEBUG_LIMIT]
        print("DEBUG LIMIT: Truncated laws to first " + str(DEBUG_LIMIT) + " laws.")

    # For each law, rate it using the LLM (in parallel)
    results = []
    max_concurrent_requests = 5
    from concurrent.futures import ThreadPoolExecutor, as_completed
    with ThreadPoolExecutor(max_workers=num_workers) as executor:
        future_to_idx = {
            executor.submit(
                rate_theory_law_surprisal_repeated_sampling,
                law,
                model_str=model_str,
                max_tokens=2048,
                temperature=1.0,
                num_samples=num_samples,
                max_concurrent_requests=max_concurrent_requests
            ): idx for idx, law in enumerate(laws)
        }

        from tqdm import tqdm
        average_results = []
        for future in tqdm(as_completed(future_to_idx), total=len(future_to_idx)):
            idx = future_to_idx[future]
            try:
                result = future.result()
                results.append(result)

                # Try to get the average result
                try:
                    if (result != None):
                        average_probability_true = result.get("average_probability_true", None)
                        if (average_probability_true != None):
                            average_results.append(average_probability_true)

                except Exception as e:
                    print("ERROR processing return of `rate_theory_law_surprisal_repeated_sampling`: " + str(e))

                # Calculate the average probability of the average probabilities.
                avg_of_avg_probability_true = None
                if (len(average_results) > 0):
                    avg_of_avg_probability_true = sum(average_results) / len(average_results)

                # Pack it
                packed = {
                    "model_str": model_str,
                    "total_laws_scored": len(results),
                    "avg_of_avg_probability_true": avg_of_avg_probability_true,
                    "average_results": average_results,
                    "raw_results": results,
                }
                # Save the packed results
                print(f"Saving intermediate results to {filename_out}")
                with open(filename_out, "w") as f:
                    json.dump(packed, f, indent=4)

            except Exception as e:
                print(f"Error processing law {idx+1}: {e}")
                import traceback
                traceback.print_exc()


    print("")
    print("Surprisal / Belief Elicitation evaluation complete.")
    print("-" * 80)
    print("")
    print("Total laws evaluated: " + str(len(results)))
    print("Model used: " + model_str)
    print("Number of samples per law: " + str(num_samples))
    prob_true_str = ""
    if (packed.get("avg_of_avg_probability_true", None) != None):
        prob_true_str = str(round(packed.get("avg_of_avg_probability_true", -1), 3))

    print("Average (of average) probability that the model believes the laws to be true: " + prob_true_str)
    stdev = None
    stdev_str = ""
    try:
        import statistics
        stdev = statistics.stdev(average_results)
        stdev_str = str(round(stdev, 3))
    except Exception as e:
        stdev = None
        stdev_str = "(Error calculating stdev: " + str(e) + ")"
    print("Standard deviation of the average probabilities: " + stdev_str)
    print("")
    print("Results saved to: " + filename_out)


#
#   Main Entry Point for Surprisal Evaluation / Belief Elicitation
#
if __name__ == "__main__":
    # Step 0: Load API keys
    loadAPIKeys()

    # Step 1: Define the input file of laws
    # File defining the laws to evaluate (see EvaluationLLMAsAJudge.py for how to generate this)
    filename_single_laws_out = "theorystore-example-single-laws.json"

    # Step 2: Do the surprisal / belief elicitation evaluation
    do_llm_law_evaluation_surprise(
        filename_in = filename_single_laws_out,
        model_str = "gpt-4.1-2025-04-14",   # Model to use for surprisal evaluation/belief elicitation. In the Theorizer paper, this was chosen to be the same model as was used to generate the theories.
        num_workers = 20,                   # Number of parallel workers to use when evaluating different theories. Internally scaled by x5 (so the real number of concurrent requests may be up to num_workers * 5).
        num_samples = 10,                   # Number of samples to take per law to estimate surprisal. Likely shouldn't be lower than 10, but many more samples may not increase accuracy much (but will increase costs).
        DEBUG_LIMIT = 0                     # Set to a positive integer to limit the number of laws processed for debugging.
    )